### ISSUE TITLE
.NET bindings: update unix test script and docs

### ISSUE THREAD

**Issue by BitFlipp** [BitFlipp/jinx#30]
* VB binding: include in unix test script and update docs
* C# binding: update unix test script to build with new assembly requirements and update docs

**Comment by Top-Ranger** [comment]
C# binding: Fixed in 3dc77ffd5691c149a35ac685bbf0f3889bdcafb0

**Comment by Top-Ranger** [comment]
Visual Basic binding does not seem to work with mono. Added the information in e7036593f3478813aa86910fb328aa5eb035b588. Reopen this when the Visual Basic compiler works with mono (or any Visual Basic compiler).
